import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/organizational/app-sidebar";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import { Separator } from "@/components/ui/separator";
import BreadcrumbClient from "@/components/organizational/breadcrumb-client";

const bricolage = Bricolage_Grotesque({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={bricolage.className}>
        <SidebarProvider className="flex">
          <AppSidebar />
          <main className="flex flex-col w-full">
            <header className="flex h-16 shrink-0 items-center gap-2 border-b px-4">
              <SidebarTrigger className="-ml-1" />
              <Separator orientation="vertical" className="mr-2 h-4" />
              <BreadcrumbClient />
            </header>
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
